# Generated by Django 5.1.6 on 2025-03-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(default=0, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
