# Generated by Django 5.1.6 on 2025-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_remove_news_photo_news_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/'),
        ),
    ]
